package com.Towrevo.network

const val dummyEmail="krupa.vrinsofts@gmail.com"
const val dummyPW="Vrin@123"
const val PREF_DEVICE_TOKEN = "device_token"
const val PREF_CATEGORY_ID = "category_id"

//api name
const val LOGIN = "login"
const val USER_REGISTER = "register"
const val COMPANY_REGISTER = "createcompany"
const val FORGOT_PASSWORD = "forgotpassword"
const val API_SEND_OTP = "resend_otp?"
const val API_COMPANY_INQUIRY_LIST = "companyInquirylist"
const val API_VERIFY_OTP = "verify_otp"
const val API_CREATE_PASSWORD = "changepassword"
const val API_UPDATE_PASSWORD = "updatepassword"
const val API_LABEL = "label"
const val API_SETTING = "settings"
const val API_LOGOUT = "logout?"
const val API_CATEGORY = "towCategory"
const val API_NEARBY_COMPANY = "CompanyList"
const val API_VIEWPROFILE = "viewProfile?"
const val API_CUSTOMER_DETAILS = "customerdetails"
const val API_CONTACT = "contact"
const val API_COMPANY_DETAILS = "customerInquirylist"
const val API_CAR_TOWS = "companydetails?"
const val API_CMS = "getcms"
const val API_USER_INQUIRY = "userInquiry"
const val API_FAQ = "faq"
const val API_COMPANY_PROFILE = "updateCompany"
const val API_CUSTOMER_PROFILE = "updateUser"
const val EMAIL = "email"
const val PASSWORD = "password"
const val IS_PHONE = "is_phone"
const val IS_VALUE = "1"
const val DEVICE_TOKEN = "device_token"


//api constant name
const val PARAM_NAME = "name"
const val PARAM_MOBILE = "mobile_number"
const val PARAM_MESSAGE = "message"
const val PARAM_DEVICE_TYPE = "device_type"
const val PARAM_USER_TYPE = "user_type"
const val PARAM_USER_ID = "user_id"
const val PARAM_OTP = "otp"
const val PARAM_PASSWORD = "password"
const val PARAM_COUNTRY_CODE = "country_code"
const val PARAM_FIRST_NAME = "first_name"
const val PARAM_LAST_NAME = "last_name"
const val PARAM_EMAIL = "email_address"
const val PARAM_DEVICE_TOKEN = "device_token"
const val PARAM_CURRENT_PASSWORD = "current_password"
const val PARAM_NEW_PASSWORD = "new_password"
const val PARAM_CONFIRM_PASSWORD = "confirm_password"
const val PARAM_I_AM_TYPE = "iam_type"
const val PARAM_IS_PHONE = "is_phone"
const val PARAM_IS_VALUE = "1"
const val PARAM_TOKEN="token"
const val PARAM_ID="id"
const val PARAM_ABOUT="about"
const val PARAM_IS_VERIFY="is_verify"
const val PARAM_ADDRESS="address"
const val PARAM_COMPANY_ID="company_id"
const val PARAM_PAGE="page"
const val PARAM_COMPANY_NAME="company_name"
const val PARAM_COMPANY_PROFILE_IMAGE="company_profile_image"
const val PARAM_WORKING_HOUR="working_hour"
const val PARAM_LATITTUDE="latitude"
const val PARAM_LONGITUDE="longitude"
const val PARAM_UPDATED_DATE="updated_date"
const val PARAM_PROFILE_IMG="profile_img"
const val PARAM_CATEGORY_ID="category_id"
const val PARAM_CMS_ID="cms_id"
const val PARAM_PROFILE_IAMGE="profile_img"
const val PARAM_INQUIRY_IAMGE="image_file[]"
